---
site_name: "CoreMeta4Cat"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
    - search.highlight
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
logo: /CoreMeta4Cat/images/CoreMeta4Cat_Picture.png

# for adding extra css/js see https://www.mkdocs.org/user-guide/customizing-your-theme/

plugins:
  - search
  - mknotebooks:
      execute: false
  - mermaid2:
      version: 11.4.1
  # TODO rebuild docs on schema change (https://github.com/dalito/linkml-project-copier/issues/39)
  # - gen-files:
  #     scripts:
  #       - gen_pages.py  # or any other name or path

watch:
  - src/catcore/schema

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Overview: overview.md
  - Design Patterns: design-patterns.md
  - How to extend: how-to-extend.md
  - Intended Users: coremeta4cat-users.md  
  # - A Hero's Journey:
    # - Introduction: a_heros_journey/a_heros_journey.md
    # - Infrastructure: a_heros_journey/infrastructure.md
    # - Workflow: a_heros_journey/workflow.md
    # - Collaborations and Future Work: a_heros_journey/collaboration_and_future.md
  - Documentation:
    - Reaction: reaction.md
    - Characterization: characterization.md
    - Synthesis: synthesis.md
    - Simulation: simulation.md
  - Schema: elements/index.md
  - About: about.md

exclude_docs: |
  /templates-linkml/

extra_css:
  - stylesheets/no-details-box.css

site_url: https://HendrikBorgelt.github.io/CoreMeta4Cat
repo_url: https://github.com/HendrikBorgelt/CoreMeta4Cat

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX

markdown_extensions:
  - md_in_html
  - admonition
  - attr_list
